version: '2'
services:
  mariadb:
    image: mariadb:10.2
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: quarkusdemo
    volumes:
      - mariadb:/var/lib/mysql

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  quarkusdemo:
    image: hectorvent/quarkusdemo:native
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB_PASSWORD=quarkusdemo
      - DB_HOST=mariadb
      - JAEGER_PORT=6831

volumes:
  mariadb:
